---
title: "PEAK Neo4j Data Model"
author: "Jason Preszler"
date: "April 30, 2018"
output: html_document
---

# Node Types

 *  Course
 *  Major
 *  Minor
 *  PEAK
 *  Component: This is a sub-unit of a major of minor in which several courses could be used to satisfy a requirement. 
 *  Instructor
 
# Relationship Types

 *  Prerequisite
 *  Requirement
 *  Option
 *  Satisfies
 *  Taught_By
 *  Contact: primary faculty member for questions about major, minor, course.
 
 # Node Properties
 
 ## Courses
 
 *  id: an internally used identifier, usually combination of subject and number
 *  subject: the three letter subject code from the catalog
 *  number: the three digit course number
 *  url: link to catalog course entry
 *  name: official course name
 *  description: catalog description
 *  minCredits: number
 *  maxCredits: number, most courses have minCredits==maxCredits
 *  frequency: code for how often the course is taught as follows

    **  FS: every fall and spring
    **  ALL: every Fal, Winter, Spring
    **  W: winter only
    **  F: fall only
    **  S: spring only
    **  FO:  Fall of odd number years
    **  FE: Fall of Even number years
    **  SO:
    **  SE:
    **  WE:
    **  WO:
    **  AN: As needed or student demand, typically internships, ind. study, and other irregular or single student courses go here.

## Major

* Name
* MinCredits

## Minor

* Name
* MinCredits

## PEAK

* name: long name of PEAK, i.e. "Natural Sciences and Mathematics"
* code: three letter code, i.e. "NSM"

## Instructor

* Name
* Email
* Office
* Dept.
* phone

## Component

* Name
* Description

# Graph

The following graph depicts the basic data model, using the igraph library in R rather than dumping the schema from Neo4j (since nothing is in Neo4j yet).

```{r dmGraph, message=FALSE, warning=FALSE}
library(igraph)

g <- graph.empty(6, directed=TRUE)
init_edges <- c(1,1, 1,5, 5,2, 5,3, 2,4, 3,4, 1,6, 2,6, 3,6, 1,2, 1,3)

g <- add.edges(g, init_edges)
V(g)$name <- c("Course", "Major", "Minor", "PEAK", "Component", "Instructor")

plot(g, layout=layout.fruchterman.reingold)
```

# Additional "Course Nodes"

Besides catalog courses, there are several non-course "course" nodes that will need to be added for prerequisite and major/minor requirements.

* "Instructor Permission"
* "Senior Standing"
* "Junior or Senior Standing"
